server:
  port: 8080
  servlet:
    context-path: /complier

spring:
  application:
    name: complier
  freemarker:
   template-loader-path: classpath:/templates/
   suffix: .ftl
   charset: UTF-8
   cache: false
  web:
    resources:
      static-locations: classpath:/static/
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.hao.compiler.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

