server:
  port: 8080
  servlet:
    context-path: /complier

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: complier
  freemarker:
   template-loader-path: classpath:/templates/
   suffix: .ftl
   charset: UTF-8
   cache: false
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:h2:file:~/compilerJava/db/test;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.hao.compiler.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

