server:
  port: 80
  servlet:
    context-path: /complier

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: complier
  freemarker:
   template-loader-path: classpath:/templates/
   suffix: .ftl
   charset: UTF-8
   cache: false
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    throw-exception-if-no-handler-found: true
#  datasource:
#    url: jdbc:h2:file:~/compilerJava/db/test;DB_CLOSE_DELAY=-1;MODE=MySQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
#        master:
#          url: jdbc:h2:file:~/compilerJava/db/test;DB_CLOSE_DELAY=-1;MODE=MySQL
#          username: sa
#          password:
#          driver-class-name: org.h2.Driver
        master:
          url: jdbc:mysql://${MYSQL_HOST:192.168.3.199}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:compiler_java}?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: ${MYSQL_USER:root}
          password: ${MYSQL_PASSWORD:ks125930.}
          driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # 是否打印 SQL
    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml/*.xml  # Mapper XML 文件位置
  configuration:
    mapUnderscoreToCamelCase: true              # 自动映射下划线转驼峰命名
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印 SQL
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
logging:
  level:
    org:
      hibernate: warn # 设置整个hibernate包的日志级别为ERROR
      hibernate.SQL: warn # 单独设置SQL语句的日志级别
      hibernate.type.descriptor.sql.BasicBinder: warn # SQL参数绑定的日志级别
      # 设置为OFF可以完全关闭该包下的日志输出
      # hibernate: OFF
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.hao.compiler.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
hao-util:
  enabled: true
  print-interface: false
  enable-failsafe: true

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true