-- H2 2.2.224;
SET DB_CLOSE_DELAY -1;
;
CREATE USER IF NOT EXISTS "SA" SALT '8994f406e4586e18' HASH '45728a7ec1d852c583244c7aa90495bf99d11398e6b24e35e77a34081cec32a0' ADMIN;
CREATE CACHED TABLE "PUBLIC"."PROJECT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) DEFAULT ON NULL NOT NULL,
    "CREATE_TIME" TIMESTAMP,
    "CREATOR" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."PROJECT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PROJECT;
INSERT INTO "PUBLIC"."PROJECT" VALUES
    (1, TIMESTAMP '2025-06-24 15:13:36.682', 'wanghao', 'demoProject');
CREATE CACHED TABLE "PUBLIC"."PROJECT_RESOURCE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) DEFAULT ON NULL NOT NULL,
    "CONTENT" CHARACTER VARYING,
    "CREATE_TIME" TIMESTAMP,
    "NAME" CHARACTER VARYING(255),
    "PARENT_ID" BIGINT,
    "PROJECT_ID" BIGINT,
    "TYPE" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."PROJECT_RESOURCE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.PROJECT_RESOURCE;
INSERT INTO "PUBLIC"."PROJECT_RESOURCE" VALUES
                                            (1, NULL, TIMESTAMP '2025-06-24 15:14:39.588', 'org', NULL, 1, 'DIRECTORY'),
                                            (2, NULL, TIMESTAMP '2025-06-24 15:23:34.813', 'hao', 1, 1, 'DIRECTORY'),
                                            (5, U&'package com.example.demo;\000d\000a\000d\000aimport org.hao.core.print.PrintUtil;\000d\000aimport org.hao.spring.SpringRunUtil;\000d\000aimport org.hao.annotation.LogDefine;\000d\000aimport lombok.extern.slf4j.Slf4j;\000d\000a\000d\000a@Slf4j\000d\000apublic class Greeter {\000d\000a    public void run(){\000d\000a        sayHello("123-"+123);\000d\000a    }\000d\000a    @LogDefine("123")\000d\000a    public String  sayHello(String name) {\000d\000a        System.out.println("Hello, " + name + "!");\000d\000a        PrintUtil.BLUE.Println("name = " + name);\000d\000a        SpringRunUtil.printRunInfo();\000d\000a        log.info("name:{}",name);\000d\000a        lombok.Lombok.preventNullAnalysis("123");\000d\000a        return this.getClass().getName();\000d\000a    }\000d\000a}\000d\000a', TIMESTAMP '2025-06-24 15:29:21', 'demo.java', 2, 1, 'FILE');
